export const APP_PACKAGE = 'com.eslamielectric.android';
export const APP_ACTIVITY = 'com.eslamielectric.android.MainActivity';

/** Compose testTag exposed via semantics { testTagsAsResourceId = true } */
export function resourceId(testTag: string): string {
  return `${APP_PACKAGE}:id/${testTag}`;
}

export const Selectors = {
  navHome: 'nav_tab_home',
  navProducts: 'nav_tab_products',
  navBasket: 'nav_tab_basket',
  navAccount: 'nav_tab_account',
  homeFeatured: 'home_featured_title',
  viewAllProducts: 'btn_view_all_products',
  searchProducts: 'field_search_products',
  chipCategoryAll: 'chip_category_all',
  chipSortDefault: 'chip_sort_default',
  addToBasket: 'btn_add_to_basket',
  stepperDecrease: 'stepper_decrease',
  stepperIncrease: 'stepper_increase',
  stepperQuantity: 'stepper_quantity',
  basketLineItem: 'basket_line_item',
  basketTotal: 'basket_total',
  basketEmpty: 'basket_empty',
  checkoutProceed: 'btn_checkout_proceed',
  accountLogin: 'btn_account_login',
  guestTrack: 'btn_guest_track',
  loginEmail: 'field_login_email',
  loginPassword: 'field_login_password',
  loginSubmit: 'btn_login_submit',
  googleSignIn: 'btn_google_sign_in',
  guestTrackModeEmail: 'guest_track_mode_email',
  guestTrackModeToken: 'guest_track_mode_token',
  guestEmail: 'field_guest_email',
  guestOrderRef: 'field_guest_order_ref',
  guestToken: 'field_guest_token',
  guestTrackSubmit: 'btn_guest_track_submit',
  localeEn: 'locale_en',
  localeFa: 'locale_fa',
  productDetail: 'screen_product_detail',
  checkoutScreen: 'screen_checkout',
  checkoutPayStripe: 'btn_checkout_pay_stripe',
  checkoutResultScreen: 'screen_checkout_result',
  signupScreen: 'screen_signup',
  signupSubmit: 'btn_signup_submit',
  profileScreen: 'screen_profile',
  saveProfile: 'btn_save_profile',
  myOrdersScreen: 'screen_my_orders',
  ordersEmpty: 'orders_empty',
  notificationsScreen: 'screen_notifications',
  notificationsMaster: 'toggle_notifications_master',
  notificationsOrders: 'toggle_notifications_orders',
  notificationsBtn: 'btn_notifications',
  screenAccount: 'screen_account',
  screenBasket: 'screen_basket',
  screenForgotPassword: 'screen_forgot_password',
  screenResetPassword: 'screen_reset_password',
  screenClaimAccount: 'screen_claim_account',
  screenOrderDetail: 'screen_order_detail',
  forgotEmail: 'field_forgot_email',
  sendResetLink: 'btn_send_reset_link',
  resetPasswordSubmit: 'btn_reset_password_submit',
  claimToken: 'field_claim_token',
  claimValidate: 'btn_claim_validate',
  claimAccountSubmit: 'btn_claim_account_submit',
  claimAccountBtn: 'btn_claim_account',
  privacyPolicy: 'btn_privacy_policy',
  contactWhatsapp: 'btn_contact_whatsapp',
  whatsappFab: 'fab_whatsapp',
  editPendingBanner: 'banner_edit_pending_order',
  orderEditBeforePayment: 'btn_order_edit_before_payment',
  checkoutClaimAccount: 'btn_checkout_claim_account',
  signUp: 'btn_sign_up',
  myOrders: 'btn_my_orders',
  logout: 'btn_logout',
} as const;

/** Visible UI strings (English default locale) when no testTag exists */
export const UiText = {
  checkoutProceed: 'Proceed to checkout',
  checkoutTitle: 'Checkout',
  checkoutDelivery: 'Delivery',
  checkoutCollection: 'Collection',
  checkoutGuestDetails: 'Guest details',
  checkoutShippingAddress: 'Delivery address',
  checkoutPayStripe: 'Pay with Stripe',
  checkoutDone: 'Done',
  signupTitle: 'Create account',
  firstName: 'First name',
  signUp: 'Sign up',
  forgotPasswordTitle: 'Forgot password',
  forgotPasswordLink: 'Forgot password?',
  sendResetLink: 'Send reset link',
  profileTitle: 'Profile',
  saveProfile: 'Save profile',
  myOrders: 'My orders',
  orderDetailTitle: 'Order details',
  orderItemsHeading: 'Items',
  basketEmpty: 'Your basket is empty',
  basketRemove: 'Remove',
  logout: 'Log out',
  accountLogin: 'Sign in',
  guestTrackOrderRef: 'Order number',
  searchDefaultTerm: 'a',
  resetPasswordTitle: 'Reset password',
  resetPasswordSubmit: 'Reset password',
  claimAccountTitle: 'Create account from order',
  claimValidate: 'Validate link',
  claimAccountSubmit: 'Create account',
  claimAccountEntry: 'Create account from order',
  privacyPolicy: 'Privacy policy',
  contactWhatsapp: 'Contact us on WhatsApp',
  editBeforePayment: 'Edit before payment',
  editPendingBannerPrefix: 'You are editing unpaid order',
  checkoutClaimAccount: 'Create account from this order',
  checkoutClaimHint: 'Received a claim link',
} as const;

export type SelectorKey = keyof typeof Selectors;
